### ISSUE TITLE
The double system

### ISSUE THREAD

**Issue by blaggacao** [divnix/nosys#2]
```console
nix-repl> p = nosys inputs ({disko, ...}: {inherit (disko) packages;})

nix-repl> p.packages.
p.packages.aarch64-darwin  p.packages.x86_64-darwin
p.packages.aarch64-linux   p.packages.x86_64-linux
nix-repl> p.packages.x86_64-darwin.x86_64-linux.
p.packages.x86_64-darwin.x86_64-linux.default
p.packages.x86_64-darwin.x86_64-linux.disko
```

**Comment by nrdxp** [comment]
Is this really an issue though? If you want to passthrough another flakes packages in their entirety you can just use `_packages = disko.packages` to avoid the double sys. The expectation is that you are not defining systems yourself but relying on the function to do it for you.

**Comment by blaggacao** [comment]
> Is this really an issue though? 

Yes, it is non-concise. Othewise, nothing is an issue in a lazy language... :smile:

**Comment by blaggacao** [comment]
I think as a low level component, `nosys` shouldn't silently introduce that level of inconsistency without throwing...

**Comment by nrdxp** [comment]
The intention is to use flake-utils as an upstream if/when possible: numtide/flake-utils#83

So if we want to address it, it should be addressed there

**Comment by nrdxp** [comment]
> I think as a low level component, `nosys` shouldn't silently introduce that level of inconsistency without throwing...

A warning would require a list of all possible systems that Nix accepts. Is there such a list maintained somewhere?
